---
- name: Map dynamic inventory group to K3s excpeted groups
  hosts: all
  gather_facts: false
  tasks:
    - name: Add master to server & k3s_cluster group
      ansible.builtin.group_by:
        key: "{{ item }}"
      when: "'master' in group_names"
      loop:
        - server
        - k3s_cluster

    - name: Add worker to server & k3s_cluster group
      ansible.builtin.group_by:
        key: "{{ item }}"
      when: "'worker' in group_names"
      loop:
        - agent
        - k3s_cluster

- name: Deploy K3s cluster playbook
  ansible.builtin.import_playbook: k3s-ansible/playbooks/site.yml

- name: Fetch kubeconfig to Bastion host
  hosts: master
  become: true
  tasks:
    - name: Ensure ~/.kube directory exists on localhost
      delegate_to: localhost
      become: false
      ansible.builtin.file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0700'

    - name: Fetch kubeconfig from master node
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        flat: true
    
    - name: Replace 127.0.0.1 with master node IP in kubeconfig
      delegate_to: localhost
      become: false
      ansible.builtin.replace:
        path: /home/ubuntu/.kube/config
        regexp: '127\.0\.0\.1'
        replace: "{{ hostvars[groups['master'][0]]['ansible_host'] }}"

    - name: Ensure correct permissions on kubeconfig
      delegate_to: localhost
      become: false
      ansible.builtin.file:
        path: /home/ubuntu/.kube/config
        mode: '0600'


