name: "IaC & Ansible Validation"

on:git
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    name: "Validate Terraform & Ansible"
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Terraform Init & Validate
        run: |
          cd terraform
          terraform init -backend=false
          terraform fmt -check
          terraform validate

      - name: Ansible Syntax Check
        run: |
          cd ansible
          ansible-playbook -i inventories/ site.yml --syntax-check